name: 📄 Deploy Documentation

on:
    workflow_call:
    workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.22
  
        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            node-version: '22'

        - name: Install dependencies
          run: |
            cd ./docs
            npm ci
            cd ..

        - name: Generate CLI docs
          run: |
            go run -tags=generateDocs generateDocs.go
      
        - name: Build Docusaurus site
          run: |
            cd ./docs
            npm run build
  
        - name: Deploy versioned docs to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/build