name: Launch Own-Git Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '>=1.24'

            - name: Install dependencies
              run: go mod tidy

            - name: Create Artifact folder
              run : mkdir -p artifacts

            - name: Install go-junit-report
              run: go install github.com/jstemmer/go-junit-report/v2@latest

            - name: Run tests
              run: |
                go test -v 2>&1 ./... | go-junit-report -set-exit-code > artifacts/test.xml
            
            - name: Run Benchmark Test
              run: |
                go test -v -bench . -count 5 2>&1 | go-junit-report -out artifacts/bench.xml

            - name: Show Unit Test Report
              uses: dorny/test-reporter@v2
              if: success() || failure()  
              with:
                name: Go Tests (Unit Tests)       
                path: artifacts/test.xml
                reporter: java-junit       
            
            - name: Show Benchmark Test Report
              uses: dorny/test-reporter@v2
              if: success() || failure()  
              with:
                name: Go Tests (Benchmark Tests)       
                path: artifacts/bench.xml
                reporter: java-junit

            